# Generated by Django 3.0 on 2019-12-14 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yt_down', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_video',
            field=embed_video.fields.EmbedVideoField(default=datetime.datetime(2019, 12, 14, 12, 8, 54, 638722, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='img_src',
            field=models.CharField(default='https://www.siechem.com/wp-content/uploads/2016/09/default-video.jpg', max_length=255),
        ),
    ]
